; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-- -mcpu=hawaii -passes=amdgpu-codegenprepare -denormal-fp-math-f32=ieee %s | FileCheck -check-prefixes=CHECK,IEEE %s
; RUN: opt -S -mtriple=amdgcn-- -mcpu=hawaii -passes=amdgpu-codegenprepare -denormal-fp-math-f32=preserve-sign %s | FileCheck -check-prefixes=CHECK,DAZ %s

; --- Positive tests (should transform in IEEE mode only) ---

; Basic scalar pattern.
define float @exp2_f32_denorm_flush(float %x) {
; IEEE-LABEL: define float @exp2_f32_denorm_flush(
; IEEE-SAME: float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; IEEE-NEXT:    [[R:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[X]])
; IEEE-NEXT:    ret float [[R]]
;
; DAZ-LABEL: define float @exp2_f32_denorm_flush(
; DAZ-SAME: float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; DAZ-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; DAZ-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; DAZ-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; DAZ-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; DAZ-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float 0.000000e+00, float [[R]]
; DAZ-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float 0.000000e+00, float %r
  ret float %flushed
}

; Fast math flags are preserved on the replacement.
define float @exp2_f32_denorm_flush_fmf(float %x) {
; IEEE-LABEL: define float @exp2_f32_denorm_flush_fmf(
; IEEE-SAME: float [[X:%.*]]) #[[ATTR0]] {
; IEEE-NEXT:    [[R:%.*]] = call nnan float @llvm.amdgcn.exp2.f32(float [[X]])
; IEEE-NEXT:    ret float [[R]]
;
; DAZ-LABEL: define float @exp2_f32_denorm_flush_fmf(
; DAZ-SAME: float [[X:%.*]]) #[[ATTR0]] {
; DAZ-NEXT:    [[R:%.*]] = call nnan float @llvm.exp2.f32(float [[X]])
; DAZ-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; DAZ-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; DAZ-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; DAZ-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float 0.000000e+00, float [[R]]
; DAZ-NEXT:    ret float [[FLUSHED]]
;
  %r = call nnan float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float 0.000000e+00, float %r
  ret float %flushed
}

; Exp2 with extra uses outside the flush chain — all uses replaced.
define float @exp2_f32_extra_use(float %x, ptr %p) {
; IEEE-LABEL: define float @exp2_f32_extra_use(
; IEEE-SAME: float [[X:%.*]], ptr [[P:%.*]]) #[[ATTR0]] {
; IEEE-NEXT:    [[R:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[X]])
; IEEE-NEXT:    store float [[R]], ptr [[P]], align 4
; IEEE-NEXT:    ret float [[R]]
;
; DAZ-LABEL: define float @exp2_f32_extra_use(
; DAZ-SAME: float [[X:%.*]], ptr [[P:%.*]]) #[[ATTR0]] {
; DAZ-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; DAZ-NEXT:    store float [[R]], ptr [[P]], align 4
; DAZ-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; DAZ-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; DAZ-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; DAZ-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float 0.000000e+00, float [[R]]
; DAZ-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  store float %r, ptr %p
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float 0.000000e+00, float %r
  ret float %flushed
}

; Vector <2 x float> pattern — scalarized to two amdgcn.exp2.f32 calls.
define <2 x float> @exp2_v2f32_denorm_flush(<2 x float> %x) {
; IEEE-LABEL: define <2 x float> @exp2_v2f32_denorm_flush(
; IEEE-SAME: <2 x float> [[X:%.*]]) #[[ATTR0]] {
; IEEE-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; IEEE-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[X]], i64 1
; IEEE-NEXT:    [[TMP2:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP1]])
; IEEE-NEXT:    [[TMP4:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP3]])
; IEEE-NEXT:    [[TMP5:%.*]] = insertelement <2 x float> poison, float [[TMP2]], i64 0
; IEEE-NEXT:    [[R:%.*]] = insertelement <2 x float> [[TMP5]], float [[TMP4]], i64 1
; IEEE-NEXT:    ret <2 x float> [[R]]
;
; DAZ-LABEL: define <2 x float> @exp2_v2f32_denorm_flush(
; DAZ-SAME: <2 x float> [[X:%.*]]) #[[ATTR0]] {
; DAZ-NEXT:    [[R:%.*]] = call <2 x float> @llvm.exp2.v2f32(<2 x float> [[X]])
; DAZ-NEXT:    [[BITS:%.*]] = bitcast <2 x float> [[R]] to <2 x i32>
; DAZ-NEXT:    [[EXPFIELD:%.*]] = and <2 x i32> [[BITS]], splat (i32 2139095040)
; DAZ-NEXT:    [[ISDENORM:%.*]] = icmp eq <2 x i32> [[EXPFIELD]], zeroinitializer
; DAZ-NEXT:    [[FLUSHED:%.*]] = select <2 x i1> [[ISDENORM]], <2 x float> zeroinitializer, <2 x float> [[R]]
; DAZ-NEXT:    ret <2 x float> [[FLUSHED]]
;
  %r = call <2 x float> @llvm.exp2.v2f32(<2 x float> %x)
  %bits = bitcast <2 x float> %r to <2 x i32>
  %expfield = and <2 x i32> %bits, splat (i32 2139095040)
  %isdenorm = icmp eq <2 x i32> %expfield, zeroinitializer
  %flushed = select <2 x i1> %isdenorm, <2 x float> zeroinitializer, <2 x float> %r
  ret <2 x float> %flushed
}

; Vector <4 x float> pattern.
define <4 x float> @exp2_v4f32_denorm_flush(<4 x float> %x) {
; IEEE-LABEL: define <4 x float> @exp2_v4f32_denorm_flush(
; IEEE-SAME: <4 x float> [[X:%.*]]) #[[ATTR0]] {
; IEEE-NEXT:    [[TMP1:%.*]] = extractelement <4 x float> [[X]], i64 0
; IEEE-NEXT:    [[TMP3:%.*]] = extractelement <4 x float> [[X]], i64 1
; IEEE-NEXT:    [[TMP5:%.*]] = extractelement <4 x float> [[X]], i64 2
; IEEE-NEXT:    [[TMP7:%.*]] = extractelement <4 x float> [[X]], i64 3
; IEEE-NEXT:    [[TMP2:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP1]])
; IEEE-NEXT:    [[TMP4:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP3]])
; IEEE-NEXT:    [[TMP6:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP5]])
; IEEE-NEXT:    [[TMP8:%.*]] = call float @llvm.amdgcn.exp2.f32(float [[TMP7]])
; IEEE-NEXT:    [[TMP9:%.*]] = insertelement <4 x float> poison, float [[TMP2]], i64 0
; IEEE-NEXT:    [[TMP10:%.*]] = insertelement <4 x float> [[TMP9]], float [[TMP4]], i64 1
; IEEE-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> [[TMP10]], float [[TMP6]], i64 2
; IEEE-NEXT:    [[R:%.*]] = insertelement <4 x float> [[TMP11]], float [[TMP8]], i64 3
; IEEE-NEXT:    ret <4 x float> [[R]]
;
; DAZ-LABEL: define <4 x float> @exp2_v4f32_denorm_flush(
; DAZ-SAME: <4 x float> [[X:%.*]]) #[[ATTR0]] {
; DAZ-NEXT:    [[R:%.*]] = call <4 x float> @llvm.exp2.v4f32(<4 x float> [[X]])
; DAZ-NEXT:    [[BITS:%.*]] = bitcast <4 x float> [[R]] to <4 x i32>
; DAZ-NEXT:    [[EXPFIELD:%.*]] = and <4 x i32> [[BITS]], splat (i32 2139095040)
; DAZ-NEXT:    [[ISDENORM:%.*]] = icmp eq <4 x i32> [[EXPFIELD]], zeroinitializer
; DAZ-NEXT:    [[FLUSHED:%.*]] = select <4 x i1> [[ISDENORM]], <4 x float> zeroinitializer, <4 x float> [[R]]
; DAZ-NEXT:    ret <4 x float> [[FLUSHED]]
;
  %r = call <4 x float> @llvm.exp2.v4f32(<4 x float> %x)
  %bits = bitcast <4 x float> %r to <4 x i32>
  %expfield = and <4 x i32> %bits, splat (i32 2139095040)
  %isdenorm = icmp eq <4 x i32> %expfield, zeroinitializer
  %flushed = select <4 x i1> %isdenorm, <4 x float> zeroinitializer, <4 x float> %r
  ret <4 x float> %flushed
}

; Vector with fast math flags.
define <2 x float> @exp2_v2f32_denorm_flush_fmf(<2 x float> %x) {
; IEEE-LABEL: define <2 x float> @exp2_v2f32_denorm_flush_fmf(
; IEEE-SAME: <2 x float> [[X:%.*]]) #[[ATTR0]] {
; IEEE-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; IEEE-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[X]], i64 1
; IEEE-NEXT:    [[TMP2:%.*]] = call nnan nsz float @llvm.amdgcn.exp2.f32(float [[TMP1]])
; IEEE-NEXT:    [[TMP4:%.*]] = call nnan nsz float @llvm.amdgcn.exp2.f32(float [[TMP3]])
; IEEE-NEXT:    [[TMP5:%.*]] = insertelement <2 x float> poison, float [[TMP2]], i64 0
; IEEE-NEXT:    [[R:%.*]] = insertelement <2 x float> [[TMP5]], float [[TMP4]], i64 1
; IEEE-NEXT:    ret <2 x float> [[R]]
;
; DAZ-LABEL: define <2 x float> @exp2_v2f32_denorm_flush_fmf(
; DAZ-SAME: <2 x float> [[X:%.*]]) #[[ATTR0]] {
; DAZ-NEXT:    [[R:%.*]] = call nnan nsz <2 x float> @llvm.exp2.v2f32(<2 x float> [[X]])
; DAZ-NEXT:    [[BITS:%.*]] = bitcast <2 x float> [[R]] to <2 x i32>
; DAZ-NEXT:    [[EXPFIELD:%.*]] = and <2 x i32> [[BITS]], splat (i32 2139095040)
; DAZ-NEXT:    [[ISDENORM:%.*]] = icmp eq <2 x i32> [[EXPFIELD]], zeroinitializer
; DAZ-NEXT:    [[FLUSHED:%.*]] = select <2 x i1> [[ISDENORM]], <2 x float> zeroinitializer, <2 x float> [[R]]
; DAZ-NEXT:    ret <2 x float> [[FLUSHED]]
;
  %r = call nnan nsz <2 x float> @llvm.exp2.v2f32(<2 x float> %x)
  %bits = bitcast <2 x float> %r to <2 x i32>
  %expfield = and <2 x i32> %bits, splat (i32 2139095040)
  %isdenorm = icmp eq <2 x i32> %expfield, zeroinitializer
  %flushed = select <2 x i1> %isdenorm, <2 x float> zeroinitializer, <2 x float> %r
  ret <2 x float> %flushed
}

; --- Negative tests (should NOT transform) ---

; f64 type — not supported.
define double @exp2_f64_no_match(double %x) {
; CHECK-LABEL: define double @exp2_f64_no_match(
; CHECK-SAME: double [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[R:%.*]] = call double @llvm.exp2.f64(double [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast double [[R]] to i64
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i64 [[BITS]], 9218868437227405312
; CHECK-NEXT:    [[ISDENORM:%.*]] = icmp eq i64 [[EXPFIELD]], 0
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], double 0.000000e+00, double [[R]]
; CHECK-NEXT:    ret double [[FLUSHED]]
;
  %r = call double @llvm.exp2.f64(double %x)
  %bits = bitcast double %r to i64
  %expfield = and i64 %bits, 9218868437227405312
  %isdenorm = icmp eq i64 %expfield, 0
  %flushed = select i1 %isdenorm, double 0.000000e+00, double %r
  ret double %flushed
}

; No flush pattern — plain exp2.
define float @exp2_f32_no_flush(float %x) {
; CHECK-LABEL: define float @exp2_f32_no_flush(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    ret float [[R]]
;
  %r = call float @llvm.exp2.f32(float %x)
  ret float %r
}

; Wrong AND mask (0x7f800001 instead of 0x7f800000).
define float @exp2_f32_wrong_mask(float %x) {
; CHECK-LABEL: define float @exp2_f32_wrong_mask(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095041
; CHECK-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float 0.000000e+00, float [[R]]
; CHECK-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095041
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float 0.000000e+00, float %r
  ret float %flushed
}

; Wrong compare predicate (ne instead of eq).
define float @exp2_f32_wrong_cmp_pred(float %x) {
; CHECK-LABEL: define float @exp2_f32_wrong_cmp_pred(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; CHECK-NEXT:    [[NOTDENORM:%.*]] = icmp ne i32 [[EXPFIELD]], 0
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[NOTDENORM]], float 0.000000e+00, float [[R]]
; CHECK-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %notdenorm = icmp ne i32 %expfield, 0
  %flushed = select i1 %notdenorm, float 0.000000e+00, float %r
  ret float %flushed
}

; Select operands swapped (true=exp2, false=0.0).
define float @exp2_f32_select_swapped(float %x) {
; CHECK-LABEL: define float @exp2_f32_select_swapped(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; CHECK-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float [[R]], float 0.000000e+00
; CHECK-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float %r, float 0.000000e+00
  ret float %flushed
}

; Select true value is not zero.
define float @exp2_f32_nonzero_true_val(float %x) {
; CHECK-LABEL: define float @exp2_f32_nonzero_true_val(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; CHECK-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float 1.000000e+00, float [[R]]
; CHECK-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float 1.000000e+00, float %r
  ret float %flushed
}

; icmp RHS is non-zero.
define float @exp2_f32_cmp_nonzero(float %x) {
; CHECK-LABEL: define float @exp2_f32_cmp_nonzero(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[EXPFIELD]], 1
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[CMP]], float 0.000000e+00, float [[R]]
; CHECK-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %cmp = icmp eq i32 %expfield, 1
  %flushed = select i1 %cmp, float 0.000000e+00, float %r
  ret float %flushed
}

; Select false value is not the exp2 result.
define float @exp2_f32_false_val_not_exp2(float %x, float %other) {
; CHECK-LABEL: define float @exp2_f32_false_val_not_exp2(
; CHECK-SAME: float [[X:%.*]], float [[OTHER:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.exp2.f32(float [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast float [[R]] to i32
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and i32 [[BITS]], 2139095040
; CHECK-NEXT:    [[ISDENORM:%.*]] = icmp eq i32 [[EXPFIELD]], 0
; CHECK-NEXT:    [[FLUSHED:%.*]] = select i1 [[ISDENORM]], float 0.000000e+00, float [[OTHER]]
; CHECK-NEXT:    ret float [[FLUSHED]]
;
  %r = call float @llvm.exp2.f32(float %x)
  %bits = bitcast float %r to i32
  %expfield = and i32 %bits, 2139095040
  %isdenorm = icmp eq i32 %expfield, 0
  %flushed = select i1 %isdenorm, float 0.000000e+00, float %other
  ret float %flushed
}

; Vector: wrong mask (non-splat would not match m_APInt).
define <2 x float> @exp2_v2f32_wrong_mask(<2 x float> %x) {
; CHECK-LABEL: define <2 x float> @exp2_v2f32_wrong_mask(
; CHECK-SAME: <2 x float> [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call <2 x float> @llvm.exp2.v2f32(<2 x float> [[X]])
; CHECK-NEXT:    [[BITS:%.*]] = bitcast <2 x float> [[R]] to <2 x i32>
; CHECK-NEXT:    [[EXPFIELD:%.*]] = and <2 x i32> [[BITS]], <i32 2139095040, i32 2139095041>
; CHECK-NEXT:    [[ISDENORM:%.*]] = icmp eq <2 x i32> [[EXPFIELD]], zeroinitializer
; CHECK-NEXT:    [[FLUSHED:%.*]] = select <2 x i1> [[ISDENORM]], <2 x float> zeroinitializer, <2 x float> [[R]]
; CHECK-NEXT:    ret <2 x float> [[FLUSHED]]
;
  %r = call <2 x float> @llvm.exp2.v2f32(<2 x float> %x)
  %bits = bitcast <2 x float> %r to <2 x i32>
  %expfield = and <2 x i32> %bits, <i32 2139095040, i32 2139095041>
  %isdenorm = icmp eq <2 x i32> %expfield, zeroinitializer
  %flushed = select <2 x i1> %isdenorm, <2 x float> zeroinitializer, <2 x float> %r
  ret <2 x float> %flushed
}
